Implement token login (take 2)
Couchers-org/couchers-react pull request #16
Opened 2020-10-14 23:02 UTC by lucaslcode

2020-10-14 23:06 UTC, lucaslcode commented on src/features/login/index.tsx
> +  }, []);
Console complains about dependencies. I guess I shouldn't be using `useEffect` for this - what's the right way?

2020-10-14 23:06 UTC, lucaslcode commented on src/features/login/index.tsx
> +            ></TextInput>
This is working but it's mostly luck and breaks if I add 'disabled' (since this is the password step, not the login step), I guess due to react treating it as a different text field, so no username is sent. Is there a way around this?

2020-10-15 18:39 UTC, jpmonette commented on src/features/login/index.tsx
> +  }, []);
@lucaslcode Your array is empty.

2020-10-17 21:17 UTC, lucaslcode commented
@jpmonette this is ready for review, be brutal!

2020-10-24 00:21 UTC, darrenvong requested changes

2020-10-24 00:21 UTC, darrenvong commented on src/views/Login.tsx
> +              //key prevents react thinking this is the same input as the other username field
Really? I don't think this matters as you are not outputting `TextInputs` using a map. It usually only matters because of https://reactjs.org/docs/lists-and-keys.html#keys

2020-10-24 00:21 UTC, darrenvong commented on src/views/Login.tsx
> +            <Button onClick={onSubmit} loading={loading || authLoading}>
How does this work to determine if the user has a password or not (which I believe then decides whether to display the password field or send an email instead)? It's not clear to me how `onSubmit` can be re-used across forms and "adapt" to each one so please explain :sweat_smile: 

Might also be a sign to split this component up a bit more, with each route in its own component?

2020-10-24 00:21 UTC, darrenvong commented on src/features/auth/authActions.ts
>      setAuthToken(token);
What's the reasoning for not just having the token state in the Redux store? It's a bit unconventional to manage state outside of React component state/Redux state in my opinion without good reasons

2020-10-24 00:21 UTC, darrenvong commented on src/libs/login.ts
> +import { authClient } from "../features/api";
Couldn't this live in the `features/auth` folder instead? Feels like we are not taking advantage of feature-based folder by having them over different places rather than colocating them into the same feature folder.

2020-10-24 00:30 UTC, darrenvong commented on src/AppRoutes.tsx
> +      <PrivateRoute exact path={logoutRoute}>
This probably shouldn't be shown unless the user is actually logged in.

2020-10-24 13:49 UTC, lucaslcode commented on src/views/Login.tsx
> +              //key prevents react thinking this is the same input as the other username field
I was getting warnings in the console about switching between uncontrolled and controlled inputs. I will take the keys out to double check that's what solved it. 

I guessed that the react-router `<Switch>` only renders one route in the tree, so the inputs end up in the same spot. I think it matches on type to determine if it's the same component when there's no key.

2020-10-24 13:51 UTC, lucaslcode commented on src/features/auth/authActions.ts
>      setAuthToken(token);
This was needed to solve the circular imports. The API needs the token from the store for authentication, but the store needs the API for the actions.

2020-10-24 13:52 UTC, lucaslcode commented on src/libs/login.ts
> +import { authClient } from "../features/api";
Yeah I will have a look, I was lazy and copied all the clients from the Vue frontend

2020-10-24 13:58 UTC, lucaslcode commented on src/views/Login.tsx
> +            <Button onClick={onSubmit} loading={loading || authLoading}>
In the on submit function, it just checks if password has been set, if not it's in "step 1", checking if the user has a password. 

I guess I could split it up.  Perhaps two child components and keep the username in the state here in the parent.

2020-10-24 20:57 UTC, darrenvong commented on src/views/Login.tsx
> +              //key prevents react thinking this is the same input as the other username field
Ohh I think I see where the problem is. The warning is saying that because in the version of the form where we render both the username and password field, we're "controlling" the username field's value to whatever the hook returns (line 101). 

In the initial form (only username field is visible), we're not doing that (so it's uncontrolled) and without the key, all of the other props are the same, so it thinks we are switching from one to the other when you are go back and forth between the two. The warning is right in this case and it's saying we are being inconsistent.

It's a good warning and I think we should fix it properly rather than silencing it with the key hack. Will have a think on how to properly address this instead :sweat_smile:

2020-10-24 21:27 UTC, darrenvong commented on src/views/Login.tsx
> +            <Button onClick={onSubmit} loading={loading || authLoading}>
Yeah that's a good idea for the username/password login form, and you can show/hide it based off some toggle state.

Also, if `Login` is a page component, I think it's better to move all of the form stuff into its own component so we're free to  render more stuff that might not be related to the login form in future.

2020-10-24 22:21 UTC, darrenvong commented on src/views/Login.tsx
> +              //key prevents react thinking this is the same input as the other username field
After playing around with this a bit more... I think all of this different route switching is unnecessary and you can achieve the same result with an additional state variable, and conditionally render the form (all as uncontrolled fields) depending on the login method discovered from the GRPC call in `onSubmit`.

2020-10-26 23:23 UTC, lucaslcode commented on src/views/Login.tsx
> +              //key prevents react thinking this is the same input as the other username field
Oh I just saw this... see what you think of the latest commit. Still uses switch but seems very neat now because it's broken up.

2020-10-29 01:26 UTC, darrenvong requested changes
Mostly small changes, but definitely looks a lot neater now with the form split up. Nice work!

2020-10-29 01:26 UTC, darrenvong commented on src/AppRoutes.tsx
> +export const loginPasswordRoute = loginRoute + "/password";
```suggestion
export const loginPasswordRoute = `${loginRoute}/password`;
```
Pretty minor in this case, but template strings are less error prone if you have to glue more things together.

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/Login.tsx
> +        <Route path={`${loginRoute}/:urlToken?`}>
I'm not sure if the `urlToken` is needed here since you won't need the username to login if you have the token?

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/PasswordForm.tsx
> +        <Button onClick={onSubmit} loading={authLoading}>
```suggestion
        <Button onClick={onSubmit} loading={authLoading} type="submit">
```
Since there are two buttons, the form seems to get confused without explicitly marking this as the submit button so you can still use the Enter key to log in.

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/PasswordForm.tsx
> +  const location = useLocation<{ username?: string }>();
```suggestion
  const location = useLocation<{ username: string }>();
```
I think you can type `username` as always present since you redirect the user back to fill that in in line 36 if it's missing?

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/PasswordForm.tsx
> +        username: location.state.username!,
```suggestion
        username: location.state.username,
```
If you typed `username` as always present then you won't need the non-null assertion here anymore

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/PasswordForm.tsx
> +      {!location.state?.username && <Redirect to={loginRoute} />}
```suggestion
      {!location.state.username && <Redirect to={loginRoute} />}
```
According to the TS types, `state` is always present on the `location` object so no need to use optional chaining.

2020-10-29 01:26 UTC, darrenvong commented on src/features/auth/login/UsernameForm.tsx
> +    if (location.state?.username) {
```suggestion
    if (location.state.username) {
```

2020-10-29 10:15 UTC, lucaslcode commented on src/features/auth/login/PasswordForm.tsx
> +      {!location.state?.username && <Redirect to={loginRoute} />}
I'll double check, but I think this line (or maybe somewhere else?) was causing an error because username didn't exist on the state object (the optional chain is for username, not the state). That's why I added all the option chains on the usernames, but I'll see which ones are really necessary.

(Actually I'm not sure why it would cause an error at all, I would have thought it just returns undefined which is falsey.)

2020-10-29 22:17 UTC, lucaslcode commented on src/features/auth/login/UsernameForm.tsx
> +    if (location.state?.username) {
This is the line that was throwing. Apparently state is undefined if it has no params.

2020-10-29 22:22 UTC, lucaslcode commented
Think this is ready for merge if it all looks ok now

2020-10-30 15:37 UTC, darrenvong approved these changes
Looks good to me! :+1:

2020-10-30 20:43 UTC, lucaslcode commented
I will wait until #20 is merged because there will be some conflicts

2020-10-30 21:01 UTC, merged