[WIP] Signup
Couchers-org/couchers-react pull request #19
Opened 2020-10-22 22:50 UTC by lucaslcode

Remaining todo:

- Figure out why debounce wasn't working for username validation

- Calendar for birthdate

2020-11-08 02:40 UTC, darrenvong requested changes

2020-11-08 02:40 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <Typography variant="h3">{getValues("email")}</Typography>
Since this value comes back from an async function call, I don't think we should show the form until the email has been completely loaded, as it's possible that someone on a slow connection may start filling in the form without knowing which email they are signing up for temporarily.

2020-11-08 02:40 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +            validate: async (value) => {
This doesn't need to be an async function if you are returning a Promise explicitly and the awaitable stuff are deeply nested in the promise.

2020-11-08 02:40 UTC, darrenvong commented on src/features/auth/signup/EmailForm.tsx
> +  const authLoading = useTypedSelector((state) => state.auth.loading);
This seems to be an impossible state and so unnecessary as the user can only go to the sign up form if they are not already signed in.

2020-11-08 02:40 UTC, darrenvong commented on src/features/auth/signup/EmailForm.tsx
> +          loading={loading || authLoading}
```suggestion
          loading={loading}
```
Following from the above comment.

2020-11-08 02:40 UTC, darrenvong commented on src/features/auth/signup/lib.ts
> +export const submitEmail = async (email: string) => {
Probably a nitpick thing :sweat_smile:  but the name of this seems a little generic/unclear to me without looking at the implementation of the helper function. What does submitting an email do? Maybe rename this to `createAccount` or `signUpEmailAccount`? Something along those lines to convey this helper will sign the user email up to the platform.

2020-11-08 15:56 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    mode: "onChange",
I think definitely best to go with either the `onBlur` mode or leave it at the `onSubmit` mode. Either options would mean you don't need to use debounce anymore for the username check.

2020-11-08 22:31 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <Typography variant="h3">{getValues("email")}</Typography>
Well, they will have clicked the link from their own email anyway. What do you think? I'll put a skeleton in just the email for now.

2020-11-09 22:29 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <Typography variant="h3">{getValues("email")}</Typography>
It's a bit better than before as the form is now less "jumpy", as we don't get some new content suddenly appearing and taking up extra space. But I still think it's an odd user experience compared to most sign up forms I've used on other websites, in which the pre-filled details (things we know about the user in the system) are already there by the time you see the form. Even the Vue alpha behaves like that so I think we'll be deviating from that if we do something different here.

2020-11-09 22:32 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <Autocomplete
I'm quite glad you got this working :tada: the types on this component is very weird...

2020-11-10 00:01 UTC, darrenvong reviewed
Changes look good. Happy to approve once the remaining comments are resolved

2020-11-11 20:49 UTC, amdwit approved these changes

2020-11-11 20:49 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +  [HostingStatus.HOSTING_STATUS_CANT_HOST]: "Can't host",
Do we have to take i18n into account? i.e. labels in other languages?

2020-11-11 20:49 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <CircularProgress />
What about React.Suspense?

2020-11-11 20:49 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
Will this work correctly with non utc timezones? What is the expected value at the backend? A timestamp representing midnight utc?

2020-11-11 20:49 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +                value: /^[a-z][0-9a-z_]*[a-z0-9]$/,
this is a magic number, should go to config, or at least a variable with a descriptive name.

2020-11-11 20:49 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +                !isNaN(new Date(stringDate).getTime()) || "Not a valid date.",
Maybe datavalidation should go into a util file. Or even separate validation file.

2020-11-11 21:00 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <CircularProgress />
How would that work here? I thought the async data fetching suspense stuff was still experimental?

2020-11-11 21:03 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
I believe so, in `libs/user.ts:signup()` it turns the date object into "YYYY-MM-DD"

2020-11-11 21:05 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +  [HostingStatus.HOSTING_STATUS_CANT_HOST]: "Can't host",
Would be good, whether or not we should put it in already I'm not sure. In my own apps I do like doing it from the beginning.

2020-11-11 21:19 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +  [HostingStatus.HOSTING_STATUS_CANT_HOST]: "Can't host",
It's a good point, although are we aiming multi language support in the first few versions/iterations? If not, is it worth the additional complexity of working with an i18n library right now vs lots of string swapping later on?

2020-11-12 00:38 UTC, darrenvong requested changes
Looks good to me otherwise apart from the small changes!

2020-11-12 00:38 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +                validateBirthdate(stringDate) || "Not a valid date.",
```suggestion
              validate: validateBirthdate,
```
I think you can do that and move the return value logic into the validation function to clean this up even more?

2020-11-12 00:38 UTC, darrenvong commented on src/features/auth/signup/validation.ts
> +  return !isNaN(new Date(stringDate).getTime());
```suggestion
  return !isNaN(new Date(stringDate).getTime()) || "Not a valid date.";
```
In order to enable the clean up in the other file.

2020-11-12 00:39 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <CircularProgress />
Based on this warning on the React docs:
> Don’t rely on experimental builds of React in production apps. These features may change significantly and without a warning before they become a part of React.

I don't think it's a good idea to use Suspense or any concurrent mode related features.

2020-11-12 09:23 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +                validateBirthdate(stringDate) || "Not a valid date.",
Not sure about that. If a boolean is returned you can use that for further logic, but s string is for those humans understanding the used language.

2020-11-12 09:28 UTC, amdwit approved these changes

2020-11-12 09:28 UTC, amdwit commented on src/features/auth/signup/validation.ts
> +export function validateBirthdate(stringDate: string) {
Isn't birthdate too specific?
```suggestion
export function validateDate(stringDate: string) {
```
Or you could also check for a date in the past. But that is not needed, I think.

2020-11-12 09:30 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +  [HostingStatus.HOSTING_STATUS_CANT_HOST]: "Can't host",
We could start with treating those strings as magic numbers and putting them in a separate file. I will Google for some good solutions and think about how to start it. As for the coming time english is enough.

2020-11-12 10:38 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +        <CircularProgress />
Well, I read about it over a year ago and thought it would not be experimental anymore. But indeed it still is.
However this works:
`<React.Suspense fallback={<Loading />}>
        <UserView />
      </React.Suspense>`

and

`let userInStore = false;

function UserView(): any {
  if (userInStore) {
    return <>All kinds of user data</>;
  } else
    throw new Promise((resolve) => {
      setTimeout(() => {
        userInStore = true;
        resolve();
      }, 1e3);
    });
}
`

But I do not think using Suspense in this other way for data fetching is best practice. Although it is known for over two years: https://dev.to/andreiduca/practical-implementation-of-data-fetching-with-react-suspense-that-you-can-use-today-273m

2020-11-12 10:55 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
I meant about using new Date with strings. That is strongly discouraged.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

2020-11-12 10:59 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
It may be better to have dates represented as their ISO 8601 string representations , indeed: "YYYY-MM-DD".
That is human readable, so handy for debugging. And the loss in performance with calculations is probably minimal.

2020-11-13 10:01 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +          <Autocomplete
Change this to use `Controller`

2020-11-13 14:27 UTC, amdwit commented on src/components/CircularProgress.tsx
> +      className={`${styles.root} ${props.className}`}
Use the famous classnames package here.

2020-11-13 14:27 UTC, amdwit commented on src/components/CircularProgress.tsx
> +  const styles = useStyles();
`classes` instead of `styles`
see the material ui website

2020-11-13 14:27 UTC, amdwit commented on src/features/auth/signup/EmailForm.tsx
> +      <Typography>
This has the same semantics as `<p>` I see elsewhere. It should be unified. I prefer a custom component called P

2020-11-13 21:09 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
I don't think there's a way to easily store the form data as a date object but display as text, (especially if you want it to be typeable as well as selectable). Since the time is stripped out before it is sent to the server, I don't think we have to worry about timezones in the parsing.

2020-11-13 21:10 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +                validateBirthdate(stringDate) || "Not a valid date.",
I think I prefer as is, I'm going to leave it unless you feel strongly about it

2020-11-13 21:10 UTC, lucaslcode commented on src/features/auth/signup/validation.ts
> +export function validateBirthdate(stringDate: string) {
I broke the backend using a future date so added a check (and a bug report)

2020-11-13 21:11 UTC, lucaslcode commented on src/components/CircularProgress.tsx
> +      className={`${styles.root} ${props.className}`}
I think once outstanding PRs are merged I will do a cleanup because this is in a few places

2020-11-13 23:31 UTC, amdwit approved these changes
I still don't get it with the Date conversion.

2020-11-13 23:31 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
The problem with using new Date this way is exactly with strings like '2000-01-01'. Depending on timezone this gets translated to different Date values in different browsers. And I do not understand why it is converted to Date anyway as both backend communication and the input work with strings.

2020-11-13 23:31 UTC, amdwit commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
It is strongly discouraged. Then why would you do it?

2020-11-13 23:51 UTC, lucaslcode commented on src/features/auth/signup/CompleteSignupForm.tsx
> +    const parsedBirthdate = new Date(data.birthdate);
I didn't want the user to be typing YYYY-MM-DD as it's not very natural, but I just saw that using type="date" makes the typing user friendly but does return that format.

2020-11-14 09:05 UTC, amdwit approved these changes
Hi Lucas, of course I approve this. I hope you do not have too harsh feelings about the conversation we had. I do not. 😃

2020-11-14 10:47 UTC, lucaslcode commented
> Hi Lucas, of course I approve this. I hope you do not have too harsh feelings about the conversation we had. I do not. 😃

Not at all!

2020-11-14 10:57 UTC, merged