Remove module token state
Couchers-org/couchers-react pull request #20
Opened 2020-10-25 00:53 UTC by darrenvong

By creating the clients within the thunk payload creator, we always have access to the Redux store state, which means the auth token only needs to live in one spot and reduces confusion.

It's a bit more repeated work, but not by much. At least then the Redux store doesn't feel as useless...

2020-10-25 00:55 UTC, darrenvong commented on src/features/api.ts
> -export const requestsClient = new RequestsPromiseClient(URL, null, opts) as RequestsPromiseClient
We can bring these clients back as and when we implement new thunks or new custom hooks if we are not using Redux for part of the app without global state that needs to be persisted.

2020-10-25 01:00 UTC, darrenvong reviewed
Left a note on why I had to delete the clients in the API file.

2020-10-25 08:26 UTC, lucaslcode commented
This is much neater, but I'm not sure it's a good idea to recreate the clients with every API call. I believe they are supposed to be long-lived, and one of the benefits of grpc is that it keeps the connection open, making it faster than normal http fetches. 

Maybe @aapeliv can comment?

2020-10-25 23:24 UTC, darrenvong commented
If the goal is to keep using the same client, is there another way we can inject the auth token in every request without needing the interceptors to read from the module token state? Maybe we can supply those at request time inside the thunk?

2020-10-26 00:09 UTC, lucaslcode commented
You can indeed inject the auth token in individual requests, the client functions all have a metadata parameter and it can be put there.

However that's a pain to do for every single call, for me if the choice is between that and the current workaround, I'd choose the current one. Sure it's a messy workaround, but it's a messy workaround in one file only that works and doesn't have any (?) effect on the codebase as a whole,

2020-10-26 01:28 UTC, darrenvong commented
Yeah I agree that's too error prone, as forgetting to put a token in one place would mess up the request.

I thought I have a less destructive option by just removing the `store.subscribe` but that seems to be screwing up the redux-persist stuff :cry:. Might have to abandon this for now unless I think of a better way over the coming days...

2020-10-28 01:45 UTC, darrenvong reviewed
@lucaslcode I managed to come up with a different solution that allows us to remove the module state without deleting all those clients and having to re-create them every time. Most of the headache was fixing the circular import mess we had which made everything break if you don't import things in the right order...

Take a look again and see what you think!

2020-10-28 01:45 UTC, darrenvong commented on src/index.tsx
> +    <Provider store={store}>
Moved the `Provider` and Redux store in here instead as it's a lot easier to reason about and **guarantee** that the Redux store will be correctly loaded before any React components. This is important as `AppRoutes` was reading from the store before its setup script got properly loaded (and it was kinda by chance the specfic import order meant it worked).

It's also a convention in most projects I work in to set up/import/load stuff outside of React in the entry point.

2020-10-28 01:45 UTC, darrenvong commented on src/reducers.ts
> +import { authReducer } from "./features/auth";
This was key in breaking the circular dependency hell I was facing, as `features/auth/index.ts` gives me control on the exact order the scripts need to be imported/loaded rather than randomly guessing by moving imports around within the file... which will get trickier as this project grows. I recommend sticking to this pattern and importing that file rather than the slice/action files directly to avoid the headache I faced in future :face_with_head_bandage:

2020-10-28 14:43 UTC, lucaslcode commented on src/features/auth/index.ts
> +export * from "./authSlice";
Great work! Could you explain to me how doing an index file like this manages to avoid the circular dependency?

2020-10-29 00:16 UTC, darrenvong commented on src/features/auth/index.ts
> +export * from "./authSlice";
The idea is that when the Redux store (indirectly) imports the slice/thunk action and need that value synchronously to build the store, importing through this index file ensures the modules will be loaded in the right order. Sure, you can probably do the same by moving imports around, but it becomes harder to follow as the project grows.

Hope that makes sense as the details of it can get complicated and tbh I'm still wrapping my head around it! I adapted the idea from https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

2020-10-29 10:19 UTC, lucaslcode commented
I was getting an "Unauthorized" error when logging in (username "aapeli" and password "Aapeli's password"). Seemed like the login worked but then not the GetUser call. That probably means the session token is not being stored or not being used/updated in the interceptor. I'll investigate more tonight hopefully.

2020-10-29 10:23 UTC, lucaslcode commented
I see the problem, the session token isn't updated in the store until the thunk returns, and it calls GetUser before that (so it doesn't have a token).

2020-10-29 10:24 UTC, lucaslcode commented on src/features/auth/authActions.ts
>      const user = await getUserByUsername(username);
The token has to be updated in the store before calling this, right now it doesn't update the thunk returns.

2020-10-29 10:27 UTC, lucaslcode commented on src/features/auth/authActions.ts
>      const user = await getUserByUsername(username);
I guess we have to add the second parameter `thunkApi` in which has `dispatch`, and make a new `commitToken` action

2020-10-30 14:33 UTC, darrenvong commented on src/features/auth/authActions.ts
>      const user = await getUserByUsername(username);
I tried your approach, but it introduced a new problem. Once the token has been committed to the store via that action, the user is authenticated at that point and so the `PrivateRoute` detected that, re-rendered and got rid of the form... while the user fetching request was still happening! That meant there was a brief moment where I started seeing a flicker between "hello, user" and "hello, aapeli".

So with one workaround goes comes another... I'll write a comment directly on that shortly

2020-10-30 14:43 UTC, darrenvong commented on src/features/auth/authActions.ts
> +    const user = await getUserByUsername(username, token);
The workaround: the `getUserByUsername` optionally take in a token, which it can be used to inject into the client API calls' metadata. I think this is a ok tradeoff since we won't really need to do it in any other places as the interceptor will work as before with other requests. Whereas with the module state, the pattern is not scalable if the interceptor in future needs more state from the store, as we'll end up having to put them in both places.

2020-10-30 14:43 UTC, darrenvong commented on src/features/api.ts
> +    if (!authorizationHeader) {
Because of the workaround... we want to make sure the interceptor don't overwrite the token set, if one exists already. Otherwise it worked the same as before.

2020-10-30 18:47 UTC, lucaslcode requested changes
Just one thing then looks good to merge!

2020-10-30 18:47 UTC, lucaslcode commented on src/features/auth/authSlice.ts
> +    }
Workaround looks good, that means we don't actually need this action right?

2020-10-30 20:48 UTC, merged