Edit user info
Couchers-org/couchers-react pull request #23
Opened 2020-11-11 02:09 UTC by darrenvong

This partially covers #6, and it's essentially the "my info" tab in the alpha version of the app. Basic unit tests to come in a separate PR as I didn't want to bloat the PR size too much.

2020-11-11 02:30 UTC, darrenvong commented on src/features/profile/actions.ts
> +export const updateUser = createAsyncThunk<
Moved this action here as it doesn't really belong in auth. It's still fine for the reducers to stay in auth though as that's  [extra reducers builder](https://redux-toolkit.js.org/api/createSlice#extrareducers) is designed for slices to respond to additional action outside of those defined in it.

2020-11-11 02:33 UTC, darrenvong commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
For requests with a lot of fields... I have to say this Java-esque setter pattern is driving me a bit nuts. I think it'd be good if we can have a wrapper in the future, or write some utility code in the frontend to abstract how tedious this gets if we have to keep on doing this a lot.

2020-11-11 02:34 UTC, darrenvong reviewed
Have a look and see if this is a good start @lucaslcode

2020-11-11 10:08 UTC, lucaslcode requested changes

2020-11-11 10:08 UTC, lucaslcode commented on src/features/profile/UserInfoForm.tsx
> +      setShowAlert(true);
Needs some error handling, eg. setting name to blank or just spaces will give an error from the backend. Not sure the best way to hook that up to react. Do we need separate loading and error reducers?

2020-11-11 10:09 UTC, lucaslcode commented on src/features/profile/index.ts
> +  [K in keyof RequiredUpdateProfileReq]-?: ProtoToJsTypes<
Mind blown

2020-11-11 10:10 UTC, lucaslcode commented on src/features/profile/index.ts
> +  [K in keyof RequiredUpdateProfileReq]-?: ProtoToJsTypes<
What does the `-` do?

2020-11-11 11:46 UTC, darrenvong commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
Yeah although this makes the code super bloated where there are lots of fields and they may or may not have a value without a lot of if-statements for each one. Ideally, we should be able to pass in a config object and only set the fields if they exist in the object like:

```javascript
req.setPayload({name, city, gender})
```

How likely is it this will happen in future requests based on the API that's already been written so far? Definitely something to think about if it's gonna be recurring pain.

2020-11-11 11:58 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +import { Button, makeStyles, TextField } from "@material-ui/core";
Is there a future plan to make our own components with our own look and feel? Otherwise if we are just sticking to Material UI styles, not sure there's much value to wrap empty component shells around their component.

Anyway, assuming there is a good reason, I'm thinking the opposite direction haha and prefix things from Material UI - e.g. `MuiButton` if there can be scope for confusion. Seems to be a pattern I've seen in a few JavaScript libraries for when they show how to wrap your own code around theirs with the same name to build on top of it.

2020-11-11 12:03 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +            render={({ onChange }) => (
Yeah `setValue` in the `onChange` didn't work for me for some strange reasons. Not sure if it's to do with the fact it's a multi-value input :shrug:

But yeah I think you should use a controller, it seems to be the library's recommended pattern to register all fields in your form either with register on a ref directly, or with a Controller for more awkward components like the Autocomplete that doesn't expose a ref - https://react-hook-form.com/get-started#Registerfields

2020-11-11 12:07 UTC, darrenvong commented on src/features/profile/index.ts
> +  [K in keyof RequiredUpdateProfileReq]-?: ProtoToJsTypes<
Haha there are too many fields in this object I decided it's worth using the more weird/fancy TS type generation features.

The `-?` bit converts an optional field in an object to be required again. Actually it's not needed anymore since that's what the `RequiredUpdateProfileReq` has done through using the `Required` utility type so will remove it when I get some time to update this next

2020-11-11 12:09 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +      setShowAlert(true);
This can probably be done in the form validation step similar to what you did in the signup form, so we won't let user submit spaces

2020-11-11 12:13 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +                  <TextField
Yeah that could work if we make our `Autocomplete` wrapper more flexible... unless `params` can be controlled via the Material UI version of Autocomplete's props

2020-11-11 12:17 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +                  <TextField
Since the main thing I need to tweak the text field for in this case is to be able to set the `margin` and `variant` prop to take advantage of the in-built styling a Material UI `TextField` already has

2020-11-11 12:29 UTC, lucaslcode commented on src/features/profile/UserInfoForm.tsx
> +      setShowAlert(true);
That would still miss some built in grpc errors like if the server is inaccessible/connection has been lost.

2020-11-11 12:31 UTC, lucaslcode commented on src/features/profile/UserInfoForm.tsx
> +import { Button, makeStyles, TextField } from "@material-ui/core";
Yeah I think we mostly won't want to use the in built styling, and I'm not sure just using the theme overrides will be enough.

2020-11-11 13:04 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +      setShowAlert(true);
Oh I see, yeah will probably need some error state within this component. I think like what JP originally commented on the authSlice, it's not good to put all UI states in the Redux store since this isn't true global state.

2020-11-11 19:43 UTC, amdwit commented on src/features/profile/UserInfoForm.tsx
> +import { Button, makeStyles, TextField } from "@material-ui/core";
I am used to wrap MUI components in components specific to the project. Then it is easier to add fance animations as requested by design. I see it as the facade design pattern for components. Does it mean we should not use MUI components anymore in our other components? Event not Box or Container? hmmm..... Anyway:  I like the idea of not using html tags in our jsx.

2020-11-11 20:11 UTC, amdwit approved these changes

2020-11-11 20:11 UTC, amdwit commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
Maybe you can try `Object.entries(reqObject).reduce((result,[key,value])=>result['set'+key[0].toUpperCase()+key.slice(1)](value), req) `
But more elaborate, as you also need to find out how to wrap `value`
Can't that be found in the generated code from gRPC?

2020-11-11 21:31 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +            fullWidth
Hmm I have to say this has been bothering me and I was toying back and forth between making things "more DRY" in a previous commit - https://github.com/Couchers-org/couchers-react/pull/23/commits/da52d8985fcd69af0e9a6a3364a7d525fc396492. But I didn't like that particular method as I had to start doing weird tricks to get the default value for a field, which didn't play well with TS without a lot of type casting and that felt like a code smell.

Maybe you're right, a new component that reduces the number of props it takes might make this easier to read and it's probably a good compromise!

2020-11-11 21:41 UTC, darrenvong commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
This was the kind of code I had in mind, although it likely won't play well with TypeScript due to how dynamic this is, which means we'll either:
- end up with a lot of weird type casting, or
- having to write extra code to narrow the types properly that we wouldn't need to if we were writing in vanilla JavaScript

There's probably a better in-between third option involving clever types but don't think I know enough TS yet to offer that suggestion...

2020-11-12 12:13 UTC, amdwit commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
So type it as far as you can. It is not forbidden to use the any type. Especially not if the code is not accessible from outside the function.

2020-11-12 23:21 UTC, darrenvong commented on src/libs/user.ts
> +    .setCountriesLived(countriesLived);
I think I'll leave this for now, as after our brief discussion last night, #28 might solve this problem altogether

2020-11-13 02:12 UTC, darrenvong commented on src/features/profile/UserInfoForm.tsx
> +                  <TextField
Actually this is not available in dev yet and only on your other branch, maybe I can import this from the `components` folder in another upcoming PR when your branch is merged.

2020-11-13 10:07 UTC, lucaslcode approved these changes
lgtm!

2020-11-13 12:08 UTC, amdwit requested changes
Hi Darren, I found some things to comment.

2020-11-13 12:08 UTC, amdwit commented on src/components/Alert.tsx
> +      severity={severity}
You do not need this as it is part of otherProps. You need also to delete it from line 15

2020-11-13 12:08 UTC, amdwit commented on src/components/Alert.tsx
> +      {children}
Not needed as it is part of props, after also deleting it from line 15.

2020-11-13 12:08 UTC, amdwit commented on src/components/Alert.tsx
> +  const { children, className, severity, ...otherProps } = props;
I think it is nicer(more consistent and conventional) to deconstruct the props in the function declaration.

2020-11-13 12:08 UTC, amdwit commented on src/components/Alert.tsx
> +      className={`${styles.root} ${className}`}
Let's use the famous classnames library for this task: https://www.npmjs.com/package/classnames

2020-11-13 12:08 UTC, amdwit commented on src/components/Alert.tsx
> +  severity: MuiAlertProps["severity"];
Not needed as it is already in MuiAlertProps

2020-11-13 12:22 UTC, amdwit commented on src/features/profile/ProfileTextInput.tsx
> +  > {}
I don't think it hurts to keep all TectFieldProps

2020-11-13 12:58 UTC, amdwit commented
> lgtm!

I did not know what that means. I thought something like Lesbian-Gay-Transsexual-... but what does the M mean? But now I know better: Looks Good To Me

2020-11-13 13:00 UTC, lucaslcode commented
Most of the comments from @amdwit are my fault :D

2020-11-13 21:20 UTC, lucaslcode commented
In fact, I am going to merge this since @amdwit are all covered in #32 and happen in multiple components.

2020-11-13 21:20 UTC, merged