Chores/cleanup
Couchers-org/couchers-react pull request #34
Opened 2020-11-14 12:37 UTC by amdwit

Fixes #32

2020-11-14 20:07 UTC, darrenvong requested changes

2020-11-14 20:07 UTC, darrenvong commented on src/features/auth/login/PasswordForm.tsx
> +import TextInput from "../../../components/TextField";
```suggestion
import TextField from "../../../components/TextField";
```
For consistency

2020-11-14 20:07 UTC, darrenvong commented on src/features/auth/login/UsernameForm.tsx
> +import TextInput from "../../../components/TextField";
```suggestion
import TextField from "../../../components/TextField";
```

2020-11-14 20:07 UTC, darrenvong commented on src/features/auth/signup/CompleteSignupForm.tsx
> +import TextInput from "../../../components/TextField";
```suggestion
import TextField from "../../../components/TextField";
```

2020-11-14 20:07 UTC, darrenvong commented on src/features/auth/signup/EmailForm.tsx
> +import TextInput from "../../../components/TextField";
```suggestion
import TextField from "../../../components/TextField";
```

2020-11-14 20:25 UTC, amdwit commented on src/components/Button.tsx
>    };
I do not understand this. This function is used in the MuiButton. What comment do you mean? A github comment? Or in the code?

2020-11-14 20:30 UTC, darrenvong commented on src/components/Button.tsx
>    };
Ahh I forgot you can view these without opening the whole file view! This function is redundant since this kinda check is done by the underlying Material UI component/React anyway, as the `onClick` prop is optional.

2020-11-14 23:16 UTC, amdwit commented
Ok, done.

2020-11-14 23:20 UTC, lucaslcode commented
You'll need to update the button snapshot to pass the build checks. (Maybe we need to discuss if we should take them out for now).

2020-11-15 02:06 UTC, darrenvong commented
My vote would be to remove the snapshot test. They're pretty useless imo as they focus too much on the implementation details (the **exact** HTML) so we'll be constantly babysitting it each time we update the component even though the external behaviour may not have changed.

2020-11-15 02:09 UTC, darrenvong reviewed
Changes are fine. Although this involves changes we're still discussing in #24 so I rather not merge until we get some consensus between us first.

2020-11-15 11:41 UTC, amdwit commented
I recreated the button snapshot
I also added the levenary package as that is why the ci breaks.

2020-11-15 19:33 UTC, darrenvong commented on package.json
> +    "levenary": "^1.1.1",
What is this package being used for?

2020-11-15 19:34 UTC, darrenvong commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
Some opinion on this would be nice 😅

2020-11-15 19:35 UTC, darrenvong commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
Some opinions on this would be nice 😅

2020-11-15 19:37 UTC, darrenvong requested changes

2020-11-15 19:37 UTC, darrenvong commented on src/features/Logout.tsx
>  import { useEffect } from "react";
I think we should move this into the `auth` folder as this belongs/relates to the auth feature.

2020-11-15 20:01 UTC, amdwit commented on package.json
> +    "levenary": "^1.1.1",
bable uses it I saw in the ci error. But I do not know what for. It has to do with levenshtein distance. So maybe it is for giving suggestions after finding an unknown word.

2020-11-15 20:36 UTC, lucaslcode commented on package.json
> +    "levenary": "^1.1.1",
I don't think this is necessary, it's a dependency and the CI error was just because the cache was messed up after updating `react-scripts` (I cleared it)

2020-11-15 21:08 UTC, amdwit commented on package.json
> +    "levenary": "^1.1.1",
Then I will remove it again.

2020-11-16 14:12 UTC, darrenvong requested changes
Only minor changes left! Good job on cleaning up everything on that checklist

2020-11-16 14:12 UTC, darrenvong commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
Some opinions on this would be nice 😅

2020-11-16 14:12 UTC, darrenvong commented on package.json
> +    "levenary": "^1.1.1",
Can you remove it in this file and do a `yarn install` again? It's still in this and the lock file 🤔

2020-11-16 14:15 UTC, darrenvong commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
Resolving this as it seems to be hidden in the main thread now we have too many messages 😬

2020-11-16 14:49 UTC, amdwit commented
I deleted levenary, now the error is back. How to solve that? Do I have to reset react-scripts? How?

2020-11-16 14:52 UTC, amdwit commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
Ah, ok, I will make it required again.

2020-11-16 14:56 UTC, amdwit commented on src/components/Alert.tsx
> -  severity: MuiAlertProps["severity"];
It is fine with me to make it required if there is no meaningful default value.

2020-11-16 15:46 UTC, amdwit commented
I deleted node-modules and yarn.lock locally and installed again. Now the Levenary error is gone.

2020-11-16 19:50 UTC, darrenvong approved these changes

2020-11-16 19:51 UTC, darrenvong commented
I had these weird errors when I updated to install Storybook too. Glad the standard delete and re-install fixed it 👍

2020-11-16 19:52 UTC, merged